services:
  back:
    build:
      args:
          user: sammy
          uid: 1000
      context: ./back
      dockerfile: ../Dockerfiles/php/php.docker
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./back:/var/www
    env_file:
      - ./back/.env
    networks:
      - flink

  front:
    build:
      context: ./front
      dockerfile: ../Dockerfiles/vue/vue.dev.docker
    command: npm run dev
    volumes:
      - ./front:/app
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - flink

  db:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=admin
    volumes:
      - data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d  # Ajout du volume pour le script d'initialisation

    networks:
      - flink

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./back:/var/www
      - ./Dockerfiles/nginx:/etc/nginx/conf.d
    networks:
      - flink

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8081:80"
    networks:
      - flink

  smtp:
    platform: linux/x86_64
    image: mailhog/mailhog
    container_name: docker-workspace-smtp
    logging:
      driver: 'none'
    ports:
      - "8003:1025"
      - "8100:8025"
    networks:
      - flink

volumes:
  data:

networks:
  flink:
    driver: bridge